package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"github.com/rkennel/ryan-learns-actions/api/graph/model"
)

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context) ([]*model.Organization, error) {
	dataRetrievalFlags := r.GetDataRetrievalFlags(ctx)
	return retrieveOrganizations(dataRetrievalFlags, r)
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, id string) (*model.Organization, error) {
	dataRetrievalFlags := r.GetDataRetrievalFlags(ctx)
	return retrieveOrganizationByID(r, dataRetrievalFlags, id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
