# Deploy to Cloud Run
# https://github.com/marketplace/actions/deploy-to-cloud-run
name: api-deploy-to-cloud-run

on:
  workflow_dispatch:
  workflow_call:

  deploy-to-cloud-run:
    name: Deploys container to cloud run
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          workload_identity_provider: projects/1001778027632/locations/global/workloadIdentityPools/big-workload-identity-pool/providers/bigwig-provider
          service_account: bigwig-service-account@bigwig-399216.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'bigwig-api'
          image: 'us-central1-docker.pkg.dev/bigwig-399216/bigwig-repository/bigwig-api'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'